{{- if $.Values.secrets }}
{{- range $name, $v := $.Values.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $name }}
spec:
  data:
  - secretKey: "{{ $v.key }}"
    remoteRef:
      key: "{{ $v.awssm }}"
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: "{{ $name }}"
{{ end }}
{{ end }}