name: python-api
replicaCount: 1
image:
  repository: 851725191021.dkr.ecr.us-east-2.amazonaws.com/python-api
  pullPolicy: Always
  tag: "latest"
service:
  type: ClusterIP
  port: 8000
  targetport: 8000
resources: 
  requests:
    cpu: 100m
    memory: 200Mi
container:
  port: 8000
secrets:
  postgres-db-url:
    awssm: postgres-db-url
    key: DB_URL
  postgres-password:
    awssm: postgres-password
    key: postgres-password 
envSecrets:
 - postgres-db-url
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
health:
  path: "/health"
  port: 8000
runAsUser: 0
postgresql: 
  auth:
    username: postgres
    existingSecret: postgres-password