name: python-api
replicaCount: 1
image:
  repository: 851725191021.dkr.ecr.us-east-2.amazonaws.com/python-api
  pullPolicy: Always
  tag: "latest"
service:
  type: ClusterIP
  port: 8000
  targetport: 8000
resources: 
  requests:
    cpu: 100m
    memory: 200Mi
container:
  port: 8000
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
health:
  path: "/health"
  port: 8000
runAsUser: 0
postgresql: 
  global:
    postgresql:
      auth:
        username: postgres
        password: postgres